### ISSUE TITLE
V0.9.5

### ISSUE THREAD

**Issue by RSDamasceno** [jcgruenhage/PlayMusicExporter#19]
Where do I download v0.9.5 apk?

**Comment by ghost** [comment]
Install the FDroid app, it will be available in a few days (FDroid now compile, sign and distribute it).  If you want it sooner, compile from source :-)

**Comment by RSDamasceno** [comment]
Thank you for explanation! I'll wait patiently! ;)

**Comment by jcgruenhage** [comment]
As you can see [here](https://gitlab.com/fdroid/fdroiddata/commit/b6a316498aad52a497dc6eec458cff7c03aa4502), the current build is already included in their data repository, and since it has been a few days, since the last time the last builds were pushed out, we will probably see new builds rather soon.

**Comment by ghost** [comment]
Build status should be posted here.  

https://f-droid.org/wiki/page/re.jcg.playmusicexporter/lastbuild

**Comment by ghost** [comment]
Hmm, failing build. :-(

"Warning: License for package Android Support Repository not accepted.". I think it's a FDroid build issue.

**Comment by jcgruenhage** [comment]
I'm going to look into it later today.. Would be nice to at least know which library is the cause for this ^^

**Comment by ghost** [comment]
It looks like a problem FDroid side, i found other projects that previously build that now fail with the same error.

For example: https://f-droid.org/wiki/page/com.simplemobiletools.calendar

**Comment by ghost** [comment]
And this https://gitlab.com/fdroid/fdroiddata/issues/619

**Comment by jcgruenhage** [comment]
Well, downgrading from 25.2.0 to 25.0.0 would probably fix it, but that feels very wrong, fdroid will surely fix that soon ^^

**Comment by jcgruenhage** [comment]
Well, all those libs that they are getting errors on, are open source. If they are open source, we should be able to build them automatically without having to accept some license first. Wouldn't it be better, if F-Droid just used a different source for them?

Edit: Nevermind, thats actually what they are doing, they just haven't refreshed their sources yet ;D

**Comment by jcgruenhage** [comment]
Until they refresh their sources, here comes v0.9.5.1, a build that is just the same as 0.9.5, but with downgraded libraries. They should be able to build that now.

**Comment by RSDamasceno** [comment]
https://f-droid.org/wiki/page/re.jcg.playmusicexporter/lastbuild_107

Failed again :/

**Comment by jcgruenhage** [comment]
I guess I'll have to check every single library again, to get what is messing that up. The most likely reason would be, that they are not only not on r44, but haven't upgraded to r43 yet either, which would make the version selection of v0.9.5.1 wrong, since r42 has even older versions..
