### ISSUE TITLE
I can't find this in f-droid.org 

### ISSUE THREAD

**Issue by RSDamasceno** [jcgruenhage/PlayMusicExporter#20]
![Screenshot_20170316-190313.png](http://i.imgur.com/ilEsqCR.png)

**Comment by jcgruenhage** [comment]
Yeah, sorry about that. 
The F-Droid build server needs to be updated to build our app, because it still uses old libraries. Look here:
https://gitlab.com/fdroid/fdroidserver/merge_requests/213

**Comment by jcgruenhage** [comment]
I'll keep this open, so that people see this :D

**Comment by RSDamasceno** [comment]
Would not it be easier to keep the updates here?
Or worse at both?

**Comment by jcgruenhage** [comment]
It would not be easier, because I'd then have to care of the keystore used to sign the releases, and now F-Droid does that. The problem right now will hopefully go away rather soon, they are actively working on fixing their build server.

**Comment by ghost** [comment]
Now available in FDroid app!!!!
