### ISSUE TITLE
Export in .m4a

### ISSUE THREAD

**Issue by ghost** [jcgruenhage/PlayMusicExporter#37]
Hi. please add an option to export music in .m4a format (best quality)

**Comment by jcgruenhage** [comment]
That won't help for music that is stored as an mp3 by google play music internally.

**Comment by ghost** [comment]
Ok, but for other music could work?

**Comment by jcgruenhage** [comment]
What? This app only exports music from Goole Play, and Google Play currently only uses mp3, so converting stuff to m4a will only result in a loss of quality.

**Comment by star2gates** [comment]
Not true, some songs/albums  use m4a.

**Comment by jcgruenhage** [comment]
Are you sure? I haven't had that on my devices yet. There were some reports, but those have vanished a few months back, it looked like Google was experimenting a bit and then decided to keep using mp3s for now.

**Comment by star2gates** [comment]
Oh, ok. Thanks. I will subscribe again now that they are not using m4a.

**Comment by jcgruenhage** [comment]
What? It would be great *if* they used m4a :D

**Comment by star2gates** [comment]
Why? Sound quality? The m4a's i saw being downloaded were lower quality than the mp3's.

**Comment by jcgruenhage** [comment]
Bitrate or quality? M4As use better algorithms to compress music, which means you find more "sound quality" in the same bitrate, or the same quality in a lower bitrate. 192 kbit/s M4As usually sound better than 320kbit/s MP3s

**Comment by star2gates** [comment]
I ment that when i ran those files though spek it showed that they wer clipped around 16kHz while the mp3's went all the way to 22kHz.

**Comment by jcgruenhage** [comment]
ahh, okay, that is worse.

**Comment by J05HI** [comment]
Use a converter to convert MP3 to M4A

**Comment by jcgruenhage** [comment]
I don't even see the benefit to do that, since every conversion leads to data loss.
