### ISSUE TITLE
Similar function for Movies/Books?

### ISSUE THREAD

**Issue by ghost** [jcgruenhage/PlayMusicExporter#38]
Hi. Is there a chance to "enhance" this application so you work with movies or books? Or maybe create other applications that are appropriate to the purpose?

**Comment by jcgruenhage** [comment]
There are no plans to extend this, mostly because I don't have the time to look into how google stores the files internally, and how to get decrypted copies of those files then.

**Comment by ghost** [comment]
I understand. However, I want anyway leave open in the case some other developer wanted to try to add this function or simply as "future feature" ..

**Comment by jcgruenhage** [comment]
It is completely out of the scope of this app. Sorry.

**Comment by ghost** [comment]
OK, thank you the same. But if you had to find the time, please do it

**Comment by jcgruenhage** [comment]
The list of things I want to do is very long, and that is somewhere near the bottom, priority wise, so it is *very, very unlikely* that this will happen.
