### ISSUE TITLE
 Automated exports happen regardless of UI preference.

### ISSUE THREAD

**Issue by ghost** [jcgruenhage/PlayMusicExporter#4]
(develop branch) Automated exports still happen even when "Enable Automatic Export" is disabled in the settings UI.    It's a bit hard to trap, as it's going through services and intents, but I know it's occurring, as I have a different path set of Auto Exports, (even though they are switched off), and my entire collection keeps appearing there, even after I delete it.

**Comment by jcgruenhage** [comment]
Are you already on to this, or should I take a look?

**Comment by ghost** [comment]
Not looked at it yet, should be able to take a look during the next week.

**Comment by jcgruenhage** [comment]
I just took a look, just about ten lines of code to write, should be able to fix that tomorrow, still got stuff to do today :D

**Comment by jcgruenhage** [comment]
Since the overwrite preference is done, that branch should have been merged long ago, we should really start branching some more :D

**Comment by jcgruenhage** [comment]
Fixed in https://github.com/jcgruenhage/PlayMusicExporter/commit/c52f99fbf02b316e431cd8cebf9bb8a8f91e0efb.
@mgillespie what do you think, v0.9.4 now?

**Comment by ghost** [comment]
Yep, no new issues I can see, auto exports don't happen now when not required, UI exports are working, and everything seems in order here.

**Comment by jcgruenhage** [comment]
Then I'll do the release later today :)

**Comment by jcgruenhage** [comment]
It is released, we had 35 downloads across all releases till now.
