### ISSUE TITLE
Switch from Java to Kotlin?

### ISSUE THREAD

**Issue by J05HI** [jcgruenhage/PlayMusicExporter#48]
@jcgruenhage

Should we do that?

**Comment by jcgruenhage** [comment]
I am not that familiar with Kotlin (contrary to Java, which I am very familiar with), so I wouldn't do it... I've heard a lot of good things about people liking Kotlin though, so I might look into it. Focusing my language learning on rust though atm.

**Comment by J05HI** [comment]
@jcgruenhage 

Okay then I'll close it. 
It's not so important to do that.
