### ISSUE TITLE
I gave Play Music exporter root access running on Nox App player on mac but it constantly gives a message unfortunately it stopped working!

### ISSUE THREAD

**Issue by ayan-das1234** [jcgruenhage/PlayMusicExporter#57]
I gave Play Music exporter root access running on Nox App player on mac but it constantly gives a message unfortunately it stopped working!

**Comment by J05HI** [comment]
Sorry but it's currently not maintained anymore.
So I can't confirm that it works

**Comment by J05HI** [comment]
@ayan-das1234
If you like you can take a look at [this amazing project](https://git.teknik.io/SMLoadrDev/SMLoadr)
