### ISSUE TITLE
Reload Play Music Files

### ISSUE THREAD

**Issue by mugel0190** [jcgruenhage/PlayMusicExporter#8]
The offline tracks are reloaded, when the app starts. It would bei nice to have a reload button. 

Thanks in advance :-)

**Comment by jcgruenhage** [comment]
I'll look into it when I have time again, I have some exams to pass first :D
Thank you for the proposal though :)

**Comment by mugel0190** [comment]
Never mind. Just take your time and good luck with your exams :-)
